import type { McpServer } from '@modelcontextprotocol/server'
import { z } from 'zod'
import {
  createAddChange,
  createChangeId,
  createRemoveChange,
  createSetCommanderChange,
  createSetNoteChange,
  createSetPrintingChange,
  createSetSectionChange,
  createUnsetCommanderChange,
  type CardChange,
  type ChangeEvent,
} from '../../change-event'
import { parseChangeBundle } from '../../editor/change-bundle'
import {
  isToSectionInvalid,
  TO_SECTION_DECK_ONLY_MESSAGE,
  type RemoveCommitItem,
  type RemoveCommitRequest,
  type SelectedMoveItem,
  type SelectedMoveRequest,
} from '../../admin/api/move'
import type { DeckCreateRequest } from '../../admin/api/deck-create'
import type { ImportCsvRequest } from '../../admin/api/import-csv'
import { callApi } from '../dispatch'
import { mutateDeck, mutateList } from '../mutations'
import { jsonResult, textResult } from '../result'
import {
  cardIdField,
  cardNameField,
  collectorNumberField,
  conditionField,
  conditionSchema,
  copyIndexField,
  deckFormatSchema,
  finishField,
  finishSchema,
  listTypeSchema,
  quantityField,
  refineDeckOnlyFormat,
  sectionField,
  setField,
  slugField,
} from '../schemas'

/**
 * `POST /api/import-deck` body as the MCP tool builds it. Looser than the
 * handler's `ImportDeckRequest` union on purpose: the tool schema leaves
 * `url`/`content` optional so a missing one surfaces as the handler's own
 * 400 rather than a schema rejection with less context.
 */
type ImportDeckBody = {
  mode: 'url' | 'text'
  url?: string
  content?: string
  name?: string
  overwrite?: boolean
}

/**
 * One card move, addressed by identity: source list + card name (plus cardId /
 * copyIndex to pin the exact entry) and a destination list. `cardId` must match
 * the entry's persistent `&N` id whenever the entry has one (`load_list` shows
 * it) — a name-only item matches only entries without an id.
 */
const moveItemSchema = z
  .object({
    listType: listTypeSchema.describe('Source list type.'),
    slug: slugField.describe('Source list slug.'),
    cardName: cardNameField.describe('Exact card name of the entry to move.'),
    cardId: cardIdField.describe(
      'The entry’s persistent card ID (the &N suffix). Required to match when the entry has one.',
    ),
    copyIndex: copyIndexField,
    toListType: listTypeSchema.describe('Destination list type.'),
    toSlug: z.string().min(1).describe('Destination list slug.'),
    toSection: z
      .string()
      .min(1)
      .optional()
      .describe('Destination deck section (deck destinations only; created when missing).'),
    set: setField,
    collectorNumber: collectorNumberField,
    finish: finishSchema.optional().describe('Override the finish on arrival.'),
    condition: conditionSchema.optional().describe('Override the condition on arrival.'),
  })
  .superRefine((val, ctx) => {
    if (isToSectionInvalid(val.toSection, val.toListType)) {
      ctx.addIssue({ code: 'custom', message: TO_SECTION_DECK_ONLY_MESSAGE })
    }
  })

/** One card removal, addressed by identity like {@link moveItemSchema}'s source half. */
const removeItemSchema = z.object({
  listType: listTypeSchema.describe('List type.'),
  slug: slugField,
  cardName: cardNameField.describe('Exact card name of the entry to remove.'),
  cardId: cardIdField.describe(
    'The entry’s persistent card ID (the &N suffix). Required to match when the entry has one.',
  ),
  copyIndex: copyIndexField,
})

/** Optional identity fields on an `apply_changes` change; missing values are autofilled. */
const changeIdField = z
  .string()
  .min(1)
  .optional()
  .describe('Change ID; autogenerated when omitted.')
const changeTimestampField = z
  .number()
  .int()
  .optional()
  .describe('Epoch-milliseconds timestamp; autofilled when omitted.')

/** Fields shared by every card-level change in `apply_changes`. */
const changeBase = {
  id: changeIdField,
  timestamp: changeTimestampField,
  cardName: cardNameField,
  cardId: cardIdField,
}

/**
 * The card-level {@link ChangeEvent} actions `apply_changes` accepts. Cross-list
 * moves (`move-from`/`move-to`) and section-structural events belong to the
 * dedicated tools (`move_cards`, `set_card_section`) and are rejected here.
 */
const applyChangeSchema = z.discriminatedUnion('action', [
  z.object({
    action: z.literal('add'),
    ...changeBase,
    set: setField,
    collectorNumber: collectorNumberField,
    finish: finishSchema.optional(),
    condition: conditionSchema.optional(),
    section: sectionField,
  }),
  z.object({
    action: z.literal('remove'),
    ...changeBase,
    set: setField,
    collectorNumber: collectorNumberField,
    finish: finishSchema.optional(),
    condition: conditionSchema.optional(),
  }),
  z.object({ action: z.literal('set-finish'), ...changeBase, finish: finishSchema }),
  z.object({
    action: z.literal('set-printing'),
    ...changeBase,
    set: setField,
    collectorNumber: collectorNumberField,
    finish: finishSchema.optional(),
    condition: conditionSchema.optional(),
  }),
  z.object({
    action: z.literal('set-note'),
    ...changeBase,
    note: z.string().describe('Note text. Empty string clears the note.'),
  }),
  z.object({ action: z.literal('set-commander'), ...changeBase }),
  z.object({ action: z.literal('unset-commander'), ...changeBase }),
  z.object({
    action: z.literal('set-section'),
    ...changeBase,
    section: z.string().min(1).describe('Target section (created when missing).'),
  }),
])

type ApplyChangeInput = z.infer<typeof applyChangeSchema>

/** True only when `A` and `B` are mutually assignable (i.e. the same union). */
type SameUnion<A, B> = [A] extends [B] ? ([B] extends [A] ? true : never) : never

// Compile-time exhaustiveness: every card-level ChangeEvent action must be either
// covered by applyChangeSchema or intentionally rejected here (the cross-list moves
// belong to move_cards). A new card-level action added to change-event makes the
// Exclude<> below stop matching and fails this line until the action is classified.
void (true satisfies SameUnion<
  Exclude<CardChange['action'], ApplyChangeInput['action']>,
  'move-from' | 'move-to'
>)

/** Fill in the id/timestamp a hand-written change may omit, yielding a full {@link ChangeEvent}. */
function toChangeEvent(input: ApplyChangeInput): ChangeEvent {
  return { ...input, id: input.id ?? createChangeId(), timestamp: input.timestamp ?? Date.now() }
}

/**
 * Register the write tools: creating lists, importing decks/CSV/change bundles,
 * card-level edits (add/remove/set-note/set-printing/set-section/commander), the
 * batch `apply_changes` primitive, and cross-list `move_cards`/`remove_cards`.
 * Card edits go through {@link mutateList}, which loads then saves inside the one
 * call so the agent never manages content hashes.
 *
 * Most of these are additive, but `import_deck` and `import_csv` can replace an
 * existing list of the same name, and `import_changes`/`apply_changes` can remove
 * cards in bulk, so those carry the SDK's `destructiveHint` — the hint reflects
 * what the tool is capable of, not what its default mode does.
 */
export function registerWriteTools(server: McpServer): void {
  server.registerTool(
    'create_list',
    {
      title: 'Create list',
      description: 'Create a new, empty deck, collection, or wanted list.',
      inputSchema: z
        .object({
          listType: listTypeSchema,
          name: z.string().min(1).describe('Display name.'),
          format: deckFormatSchema
            .optional()
            .describe('Deck format (decks only; defaults to commander).'),
        })
        .superRefine(refineDeckOnlyFormat),
    },
    async ({ listType, name, format }) => {
      const body: DeckCreateRequest = listType === 'deck' ? { name, format } : { name }
      return jsonResult(await callApi('POST', `/api/${listType}/create`, body))
    },
  )

  server.registerTool(
    'import_deck',
    {
      title: 'Import deck',
      description: 'Import a deck from a supported URL or from pasted decklist text.',
      inputSchema: z.object({
        mode: z.enum(['url', 'text']).describe('Import source.'),
        url: z.string().optional().describe('Deck URL (mode "url").'),
        content: z.string().optional().describe('Decklist text (mode "text").'),
        name: z.string().optional().describe('Name for the imported deck (mode "text").'),
        overwrite: z.boolean().optional().describe('Overwrite an existing deck of the same name.'),
      }),
      annotations: { destructiveHint: true },
    },
    async ({ mode, url, content, name, overwrite }) => {
      const body: ImportDeckBody =
        mode === 'url' ? { mode, url, overwrite } : { mode, content, name, overwrite }
      return jsonResult(await callApi('POST', '/api/import-deck', body))
    },
  )

  server.registerTool(
    'import_csv',
    {
      title: 'Import CSV',
      description:
        'Import cards from CSV text into a deck, collection, or wanted list — creating a new list, ' +
        'overwriting one, or appending to an existing one. Columns map to card fields via a ' +
        '1-based spec like "name=1,set=2,collector-number=3" (fields: name, set, collector-number, ' +
        'condition, finish, section, quantity). Values are normalized (e.g. "Near Mint" → NM, ' +
        '"F" → foil). Rows that fail validation are reported back; the rest still import.',
      inputSchema: z
        .object({
          listType: listTypeSchema,
          name: z
            .string()
            .min(1)
            .describe('New list name (create/overwrite) or an existing list (append).'),
          mode: z
            .enum(['create', 'overwrite', 'append'])
            .optional()
            .describe('Defaults to "create", which fails if the list already exists.'),
          format: deckFormatSchema
            .optional()
            .describe('Deck format; required when creating or overwriting a deck.'),
          content: z.string().min(1).describe('Raw CSV text.'),
          columns: z
            .string()
            .min(1)
            .describe('Column mapping spec, e.g. "name=1,set=2,collector-number=3,quantity=4".'),
          hasHeader: z
            .boolean()
            .optional()
            .describe('Whether the first row is a header row. Defaults to true.'),
        })
        .superRefine(refineDeckOnlyFormat),
      annotations: { destructiveHint: true },
    },
    async ({ listType, name, mode, format, content, columns, hasHeader }) => {
      const body: ImportCsvRequest = {
        listType,
        name,
        mode,
        format,
        content,
        columns,
        hasHeader,
      }
      return jsonResult(await callApi('POST', '/api/import-csv', body))
    },
  )

  server.registerTool(
    'import_changes',
    {
      title: 'Import changes',
      description:
        'Apply a change bundle exported from the site editor (format "ritual-change-bundle", ' +
        'one or more lists) to the underlying lists. Changes are re-targeted to current ' +
        'card IDs; ones whose target card no longer exists are reported as skipped conflicts. ' +
        'The response lists per-list applied counts, conflicts, and errors.',
      inputSchema: z.object({
        json: z.string().min(1).describe('The exported change JSON, verbatim.'),
      }),
      annotations: { destructiveHint: true },
    },
    async ({ json }) => {
      // Validate locally so a malformed payload surfaces as a clear message
      // instead of a generic HTTP 400; the route re-validates the same way.
      const bundle = parseChangeBundle(json)
      if (typeof bundle === 'string') {
        return { ...textResult(`Invalid change bundle: ${bundle}`), isError: true }
      }
      return jsonResult(await callApi('POST', '/api/import-changes', bundle))
    },
  )

  server.registerTool(
    'add_card',
    {
      title: 'Add card',
      description:
        'Add a card to any list (decks increment quantity if the same printing already exists). ' +
        'Supply set + collectorNumber to pin the printing. quantity adds that many copies in ' +
        'one save. Collections require set + collectorNumber together — an add without one is ' +
        'rejected.',
      inputSchema: z
        .object({
          listType: listTypeSchema,
          slug: slugField,
          cardName: cardNameField,
          set: setField,
          collectorNumber: collectorNumberField,
          finish: finishField,
          condition: conditionField,
          section: sectionField,
          quantity: quantityField,
        })
        .superRefine((val, ctx) => {
          if (val.condition !== undefined && val.listType === 'wanted') {
            ctx.addIssue({
              code: 'custom',
              message: 'condition is not tracked on wanted lists.',
            })
          }
        }),
    },
    async ({
      listType,
      slug,
      cardName,
      set,
      collectorNumber,
      finish,
      condition,
      section,
      quantity,
    }) => {
      const changes: ChangeEvent[] = Array.from({ length: quantity }, () =>
        createAddChange(cardName, { set, collectorNumber, finish, condition, section }),
      )
      return textResult((await mutateList(listType, slug, changes)).message)
    },
  )

  server.registerTool(
    'remove_card',
    {
      title: 'Remove card',
      description:
        'Remove a card from any list. Decks remove quantity copies (deleting the line at zero); ' +
        'collections and wanted lists keep one entry per physical card, so quantity must stay 1 ' +
        'there — remove entries individually (disambiguate with cardId).',
      inputSchema: z
        .object({
          listType: listTypeSchema,
          slug: slugField,
          cardName: cardNameField,
          cardId: cardIdField,
          set: setField,
          collectorNumber: collectorNumberField,
          finish: finishSchema.optional().describe('Match only entries with this finish.'),
          condition: conditionSchema.optional().describe('Match only entries with this condition.'),
          quantity: quantityField.describe('Copies to remove (decks only; default 1).'),
        })
        .superRefine((val, ctx) => {
          if (val.quantity > 1 && val.listType !== 'deck') {
            ctx.addIssue({
              code: 'custom',
              message:
                'Collections and wanted lists keep one entry per physical card; remove entries ' +
                'one at a time, using cardId to pick the exact entry.',
            })
          }
        }),
    },
    async ({
      listType,
      slug,
      cardName,
      cardId,
      set,
      collectorNumber,
      finish,
      condition,
      quantity,
    }) => {
      const changes: ChangeEvent[] = Array.from({ length: quantity }, () =>
        createRemoveChange(cardName, { cardId, set, collectorNumber, finish, condition }),
      )
      return textResult((await mutateList(listType, slug, changes)).message)
    },
  )

  server.registerTool(
    'set_card_note',
    {
      title: 'Set card note',
      description: 'Set (or, with an empty string, clear) the note on a card in any list.',
      inputSchema: z.object({
        listType: listTypeSchema,
        slug: slugField,
        cardName: cardNameField,
        cardId: cardIdField,
        note: z.string().describe('Note text. Empty string clears the note.'),
      }),
    },
    async ({ listType, slug, cardName, cardId, note }) => {
      const change = createSetNoteChange(cardName, { note, cardId })
      return textResult((await mutateList(listType, slug, [change])).message)
    },
  )

  server.registerTool(
    'set_card_printing',
    {
      title: 'Set card printing',
      description:
        'Set the printing (set/collector number/finish/condition) of a card in any list. ' +
        'Omit set and collectorNumber to clear the specific printing on a deck or wanted-list ' +
        'card; collections require both together, so omitting them there is rejected.',
      inputSchema: z.object({
        listType: listTypeSchema,
        slug: slugField,
        cardName: cardNameField,
        cardId: cardIdField,
        set: setField,
        collectorNumber: collectorNumberField,
        finish: finishField,
        condition: conditionField,
      }),
    },
    async ({ listType, slug, cardName, cardId, set, collectorNumber, finish, condition }) => {
      const change = createSetPrintingChange(cardName, {
        set,
        collectorNumber,
        finish,
        condition,
        cardId,
      })
      return textResult((await mutateList(listType, slug, [change])).message)
    },
  )

  server.registerTool(
    'set_card_section',
    {
      title: 'Set card section',
      description: 'Move a card to a section of its list (the section is created when missing).',
      inputSchema: z.object({
        listType: listTypeSchema,
        slug: slugField,
        cardName: cardNameField,
        cardId: cardIdField,
        section: z.string().min(1).describe('Target section name (exact; created when missing).'),
      }),
    },
    async ({ listType, slug, cardName, cardId, section }) => {
      const change = createSetSectionChange(cardName, section, cardId)
      return textResult((await mutateList(listType, slug, [change])).message)
    },
  )

  server.registerTool(
    'set_commander',
    {
      title: 'Set commander',
      description: 'Move a card into a deck’s Commander section.',
      inputSchema: z.object({ slug: slugField, cardName: cardNameField, cardId: cardIdField }),
    },
    async ({ slug, cardName, cardId }) => {
      const change = createSetCommanderChange(cardName, { cardId })
      return textResult((await mutateDeck(slug, [change])).message)
    },
  )

  server.registerTool(
    'unset_commander',
    {
      title: 'Unset commander',
      description: 'Move a card out of a deck’s Commander section back into the main section.',
      inputSchema: z.object({ slug: slugField, cardName: cardNameField, cardId: cardIdField }),
    },
    async ({ slug, cardName, cardId }) => {
      const change = createUnsetCommanderChange(cardName, { cardId })
      return textResult((await mutateDeck(slug, [change])).message)
    },
  )

  server.registerTool(
    'apply_changes',
    {
      title: 'Apply changes',
      description:
        'Apply an ordered batch of card-level changes (add/remove/set-finish/set-printing/' +
        'set-note/set-commander/unset-commander/set-section) to one list atomically: one load, ' +
        'one save, one changelog block. Missing change ids/timestamps are autofilled. On a ' +
        'collection, add and set-printing require set + collectorNumber together. For ' +
        'cross-list moves use move_cards.',
      inputSchema: z.object({
        listType: listTypeSchema,
        slug: slugField,
        changes: z.array(applyChangeSchema).min(1).describe('Changes to apply, in order.'),
      }),
      // Like import_changes: a change batch can remove cards in bulk.
      annotations: { destructiveHint: true },
    },
    async ({ listType, slug, changes }) => {
      const events: ChangeEvent[] = changes.map(toChangeEvent)
      return textResult((await mutateList(listType, slug, events)).message)
    },
  )

  server.registerTool(
    'move_cards',
    {
      title: 'Move cards',
      description:
        'Move cards between lists in one atomic batch. Each move names its source entry ' +
        '(listType + slug + cardName, with cardId/copyIndex to pin the exact entry) and a ' +
        'destination list; set/collectorNumber/finish/condition override the printing on ' +
        'arrival, and toSection picks a destination deck section. Unresolvable moves are ' +
        'skipped and counted; notes that a destination cannot keep are reported in droppedNotes.',
      inputSchema: z.object({
        moves: z.array(moveItemSchema).min(1).describe('Moves to apply atomically.'),
      }),
    },
    async ({ moves }) => {
      const body: SelectedMoveRequest = {
        moves: moves.map(
          (m): SelectedMoveItem => ({
            listType: m.listType,
            listSlug: m.slug,
            name: m.cardName,
            cardId: m.cardId,
            copyIndex: m.copyIndex,
            toType: m.toListType,
            toSlug: m.toSlug,
            toSection: m.toSection,
            set: m.set,
            collectorNumber: m.collectorNumber,
            finish: m.finish,
            condition: m.condition,
          }),
        ),
      }
      return jsonResult(await callApi('POST', '/api/move/selected', body))
    },
  )

  server.registerTool(
    'remove_cards',
    {
      title: 'Remove cards',
      description:
        'Remove a batch of cards across lists in one atomic pass. Each item names its entry by ' +
        'listType + slug + cardName, with cardId/copyIndex to pin the exact entry. Unresolvable ' +
        'items are skipped and counted.',
      inputSchema: z.object({
        removes: z.array(removeItemSchema).min(1).describe('Cards to remove atomically.'),
      }),
    },
    async ({ removes }) => {
      const body: RemoveCommitRequest = {
        removes: removes.map(
          (r): RemoveCommitItem => ({
            listType: r.listType,
            listSlug: r.slug,
            name: r.cardName,
            cardId: r.cardId,
            copyIndex: r.copyIndex,
          }),
        ),
      }
      return jsonResult(await callApi('POST', '/api/remove/commit', body))
    },
  )
}
