import { test, expect } from '@playwright/test'

test.describe('Homepage', () => {
  test('page loads with correct title', async ({ page }) => {
    await page.goto('/')
    await expect(page.locator('header')).toContainText('Ritual')
  })

  test('deck cards are rendered in a grid', async ({ page }) => {
    await page.goto('/')
    const deckCards = page.locator('.deck-cover')
    await expect(deckCards.first()).toBeVisible()
    expect(await deckCards.count()).toBeGreaterThan(0)
  })

  test('each deck card shows name and format/count label', async ({ page }) => {
    await page.goto('/')
    const firstCard = page.locator('.deck-cover').first()
    await expect(firstCard.locator('.cover-info h2')).not.toBeEmpty()
    // Cover footer shows either the format name (e.g. "Commander") or a card
    // count fallback (e.g. "62 cards") — match either.
    await expect(firstCard.locator('.cover-cardcount')).toContainText(/Commander|Oathbreaker|cards/)
  })

  test('collections tab shows collection cards', async ({ page }) => {
    await page.goto('#/collections')
    await expect(page.locator('h1')).toContainText('My Collections')
    const collectionCards = page.locator('.deck-cover')
    await expect(collectionCards.first()).toBeVisible()
  })

  test('footer shows ritual attribution', async ({ page }) => {
    await page.goto('/')
    await expect(page.locator('footer')).toContainText('Generated by')
    await expect(page.locator('footer')).toContainText('ritual')
  })

  test('no horizontal scrollbar at default viewport', async ({ page }) => {
    await page.goto('/')
    const scrollWidth = await page.evaluate(() => document.documentElement.scrollWidth)
    const clientWidth = await page.evaluate(() => document.documentElement.clientWidth)
    expect(scrollWidth).toBeLessThanOrEqual(clientWidth + 1)
  })
})
