export type Page =
  | 'dashboard'
  | 'import-deck'
  | 'deck-editor'
  | 'list-manager'
  | 'collection-editor'
  | 'wanted-list-editor'
  | 'build-site'
  | 'cache-refresh'
  | 'archidekt-login'
  | 'settings'
  | 'audit-log'
