#!/usr/bin/env bun
import fs from 'node:fs/promises'
import path from 'node:path'

type DepLicenseEntry = {
  name: string
  version: string
  license: string
  text: string | null
  isPrimary: boolean
}

type PackageJson = {
  name?: string
  version?: string
  license?: string | { type?: string }
  devDependencies?: Record<string, string>
}

const LICENSE_FILENAMES = [
  'LICENSE',
  'LICENCE',
  'license',
  'LICENSE.md',
  'LICENCE.md',
  'license.md',
  'LICENSE.txt',
  'license.txt',
]

async function findLicenseText(pkgDir: string): Promise<string | null> {
  for (const filename of LICENSE_FILENAMES) {
    try {
      return await fs.readFile(path.join(pkgDir, filename), 'utf-8')
    } catch {}
  }
  return null
}

function resolveLicenseString(license: PackageJson['license']): string {
  if (typeof license === 'string') return license
  if (typeof license === 'object' && license !== null && typeof license.type === 'string') {
    return license.type
  }
  return 'Unknown'
}

const rootDir = path.join(import.meta.dir, '..')
const nodeModulesDir = path.join(rootDir, 'node_modules')

const packageJson = JSON.parse(
  await fs.readFile(path.join(rootDir, 'package.json'), 'utf-8'),
) as PackageJson
const devDeps: Record<string, string> = packageJson.devDependencies ?? {}

async function getInstalledPackageNames(nmDir: string): Promise<string[]> {
  const topEntries = await fs.readdir(nmDir, { withFileTypes: true })
  const dirs = topEntries.filter((e) => e.isDirectory() && !e.name.startsWith('.'))
  const scopedDirs = dirs.filter((e) => e.name.startsWith('@'))
  const regularNames = dirs.filter((e) => !e.name.startsWith('@')).map((e) => e.name)
  const scopedNames = (
    await Promise.all(
      scopedDirs.map(async (entry) => {
        const subEntries = await fs.readdir(path.join(nmDir, entry.name), { withFileTypes: true })
        return subEntries
          .filter((sub) => sub.isDirectory())
          .map((sub) => `${entry.name}/${sub.name}`)
      }),
    )
  ).flat()
  return [...regularNames, ...scopedNames]
}

const allPackageNames = await getInstalledPackageNames(nodeModulesDir)

async function processPackage(pkgName: string): Promise<DepLicenseEntry | null> {
  // Skip @types/* — type-only, no runtime code
  if (pkgName.startsWith('@types/')) return null

  const pkgDir = path.join(nodeModulesDir, pkgName)
  let pkgJsonData: PackageJson
  try {
    pkgJsonData = JSON.parse(
      await fs.readFile(path.join(pkgDir, 'package.json'), 'utf-8'),
    ) as PackageJson
  } catch {
    return null
  }

  return {
    name: pkgJsonData.name ?? pkgName,
    version: pkgJsonData.version ?? 'unknown',
    license: resolveLicenseString(pkgJsonData.license),
    text: await findLicenseText(pkgDir),
    isPrimary: pkgName in devDeps,
  }
}

const results = await Promise.all(allPackageNames.map(processPackage))
const entries: DepLicenseEntry[] = results.filter((e): e is DepLicenseEntry => e !== null)

entries.sort((a, b) => {
  if (a.isPrimary !== b.isPrimary) return a.isPrimary ? -1 : 1
  return a.name.localeCompare(b.name)
})

const primaryCount = entries.filter((e) => e.isPrimary).length
const transitiveCount = entries.length - primaryCount

const outputPath = path.join(rootDir, 'src', 'generated', 'dep-licenses.ts')
await fs.mkdir(path.dirname(outputPath), { recursive: true })

const content =
  [
    '// AUTO-GENERATED by scripts/generate-licenses.ts — do not edit',
    '',
    'export type DepLicenseEntry = {',
    '  name: string',
    '  version: string',
    '  license: string',
    '  text: string | null',
    '  isPrimary: boolean',
    '}',
    '',
    `export const depLicenses: DepLicenseEntry[] = ${JSON.stringify(entries, null, 2)}`,
  ].join('\n') + '\n'

await fs.writeFile(outputPath, content)
console.log(`Generated ${outputPath}`)
console.log(`  ${primaryCount} primary, ${transitiveCount} transitive packages`)
