import { compareVersions } from './semver'
import type { CISystem, InitSiteConfig } from './ritual-config'

/**
 * Describes the path a managed file occupied over a version range.
 * `since`: first version this path was introduced (absent = from before versioning began).
 * `until`: first version this path is no longer used, exclusive (absent = still active).
 */
export type PathRecord = {
  path: string
  since?: string
  until?: string
}

/** A file actively generated by the current version of ritual. */
export type ActiveManagedFile = {
  ciSystem: CISystem
  paths: PathRecord[]
  generate: (config: InitSiteConfig) => string
}

/** A file that was once generated by ritual but is no longer part of the current output. */
export type HistoricalManagedFile = {
  ciSystem: CISystem
  paths: PathRecord[]
}

export type ManagedFile = ActiveManagedFile | HistoricalManagedFile

export function isActiveManagedFile(f: ManagedFile): f is ActiveManagedFile {
  return 'generate' in f
}

export type WriteMigration = { type: 'write'; path: string; content: string }
export type DeleteMigration = { type: 'delete'; path: string }
export type Migration = WriteMigration | DeleteMigration

/**
 * Returns the PathRecord covering the given version, or undefined if none applies.
 * A record covers a version when: version >= since (or since is absent)
 *                             AND version < until (or until is absent).
 */
function findPathAtVersion(paths: PathRecord[], version: string): PathRecord | undefined {
  return paths.find((record) => {
    const afterSince = record.since === undefined || compareVersions(version, record.since) >= 0
    const beforeUntil = record.until === undefined || compareVersions(version, record.until) < 0
    return afterSince && beforeUntil
  })
}

/**
 * Compute the set of file changes needed when upgrading from `fromVersion` to `toVersion`.
 *
 * For each managed file whose `ciSystem` matches the config:
 * - If the file is active at `toVersion`, its current path is written (content may have changed).
 * - If the file's path changed since `fromVersion` (rename), the old path is deleted.
 * - If the file no longer exists at `toVersion` (removal), the old path is deleted.
 *
 * Pass `fromVersion = null` for a fresh install — only writes are emitted, no deletes.
 */
export function computeMigrations(
  fromVersion: string | null,
  toVersion: string,
  files: ManagedFile[],
  config: InitSiteConfig,
): Migration[] {
  const migrations: Migration[] = []

  for (const file of files) {
    if (file.ciSystem !== config.ciSystem) continue

    const toRecord = isActiveManagedFile(file)
      ? findPathAtVersion(file.paths, toVersion)
      : undefined
    const fromRecord = fromVersion !== null ? findPathAtVersion(file.paths, fromVersion) : undefined

    // Delete the old path if it changed (rename) or the file was removed
    if (fromRecord && fromRecord.path !== toRecord?.path) {
      migrations.push({ type: 'delete', path: fromRecord.path })
    }

    // Write the current path for active files
    if (toRecord && isActiveManagedFile(file)) {
      migrations.push({ type: 'write', path: toRecord.path, content: file.generate(config) })
    }
  }

  return migrations
}
