import { render } from 'preact'
import { useState, useEffect, useCallback } from 'preact/hooks'
import type { DeckSummary, DeckDetail } from './data-types'
import { IndexPage } from './IndexPage'
import { DeckPage } from './DeckPage'

type Route = { page: 'index' } | { page: 'deck'; slug: string }

function parseHash(): Route {
  const hash = window.location.hash.replace(/^#\/?/, '')
  if (hash.startsWith('deck/')) {
    const slug = hash.slice('deck/'.length)
    if (slug) return { page: 'deck', slug }
  }
  return { page: 'index' }
}

function App() {
  const [route, setRoute] = useState<Route>(parseHash)
  const [transitioning, setTransitioning] = useState(false)
  const [visible, setVisible] = useState(true)

  // Index data
  const [deckList, setDeckList] = useState<DeckSummary[] | null>(null)
  const [useScryfallImgUrls, setUseScryfallImgUrls] = useState(true)

  // Deck data
  const [deckDetail, setDeckDetail] = useState<DeckDetail | null>(null)
  const [deckLoading, setDeckLoading] = useState(false)

  // Card modal state
  const [modalCard, setModalCard] = useState<string | null>(null)

  const navigate = useCallback(
    (newRoute: Route) => {
      if (transitioning) return
      setTransitioning(true)
      setVisible(false)

      setTimeout(() => {
        setRoute(newRoute)
        setModalCard(null)
        if (newRoute.page === 'index') {
          setDeckDetail(null)
        }
        window.scrollTo(0, 0)
        setVisible(true)
        setTransitioning(false)
      }, 200)
    },
    [transitioning],
  )

  // Hash change listener
  useEffect(() => {
    const handler = () => navigate(parseHash())
    window.addEventListener('hashchange', handler)
    return () => window.removeEventListener('hashchange', handler)
  }, [navigate])

  // Fetch index data on mount
  useEffect(() => {
    fetch('index.json')
      .then((r) => r.json())
      .then((data: { decks: DeckSummary[]; useScryfallImgUrls: boolean }) => {
        setDeckList(data.decks)
        setUseScryfallImgUrls(data.useScryfallImgUrls)
      })
      .catch((e) => console.error('Failed to load index:', e))
  }, [])

  // Fetch deck data when navigating to a deck
  useEffect(() => {
    if (route.page !== 'deck') return
    setDeckLoading(true)
    fetch(`decks/${route.slug}.json`)
      .then((r) => r.json())
      .then((data: DeckDetail) => {
        setDeckDetail(data)
        setDeckLoading(false)
      })
      .catch((e) => {
        console.error('Failed to load deck:', e)
        setDeckLoading(false)
      })
  }, [route.page === 'deck' ? route.slug : null])

  const openModal = useCallback((cardName: string) => {
    setModalCard(cardName)
  }, [])

  const closeModal = useCallback(() => {
    setModalCard(null)
  }, [])

  return (
    <div className="min-h-screen flex flex-col" style="padding: 1.5rem 2rem;">
      <header className="mb-6 flex items-center justify-between">
        <a
          href="#/"
          className="flex items-center gap-2 text-gray-400 hover:text-white transition-colors"
        >
          <img src="app.svg" alt="Ritual logo" className="h-6 w-6" />
          <span className="font-semibold text-sm">Ritual</span>
        </a>
      </header>

      <main className="grow">
        <div className={`page-transition ${visible ? 'page-visible' : 'page-hidden'}`}>
          {route.page === 'index' ? (
            deckList ? (
              <IndexPage decks={deckList} useScryfallImgUrls={useScryfallImgUrls} />
            ) : (
              <LoadingSpinner />
            )
          ) : deckLoading || !deckDetail ? (
            <LoadingSpinner />
          ) : (
            <DeckPage
              deck={deckDetail.deck}
              cards={deckDetail.cards}
              symbolMap={deckDetail.symbolMap}
              exportPath={deckDetail.exportPath}
              useScryfallImgUrls={deckDetail.useScryfallImgUrls}
              modalCardName={modalCard}
              onOpenModal={openModal}
              onCloseModal={closeModal}
            />
          )}
        </div>
      </main>

      <footer className="mt-12 border-t border-gray-800 pt-6 text-center text-xs text-gray-500">
        <p>
          Generated by{' '}
          <a href="https://github.com/sloshy/ritual" className="text-gray-400 hover:text-white">
            ritual
          </a>
        </p>
      </footer>
    </div>
  )
}

function LoadingSpinner() {
  return (
    <div className="flex items-center justify-center" style="min-height: 40vh;">
      <div className="loading-spinner" />
    </div>
  )
}

render(<App />, document.getElementById('app')!)
