import type { FunctionalComponent, ComponentChildren } from 'preact'

interface LayoutProps {
  title: string
  children: ComponentChildren
}

export const Layout: FunctionalComponent<LayoutProps> = ({ title, children }) => {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{`${title} | MTG Decks`}</title>
        <link rel="icon" type="image/svg+xml" href="app.svg" />
        <link rel="stylesheet" href="styles.css" />
      </head>
      <body className="min-h-screen flex flex-col" style="padding: 1.5rem 2rem;">
        <header className="mb-6 flex items-center justify-between">
          <a
            href="index.html"
            className="flex items-center gap-2 text-gray-400 hover:text-white transition-colors"
          >
            <img src="app.svg" alt="Ritual" className="h-6 w-6" />
            <span className="font-semibold text-sm">Ritual</span>
          </a>
        </header>
        <main className="grow">{children}</main>
        <footer className="mt-12 border-t border-gray-800 pt-6 text-center text-xs text-gray-500">
          <p>
            Generated by{' '}
            <a href="https://github.com/sloshy/ritual" className="text-gray-400 hover:text-white">
              ritual
            </a>
          </p>
        </footer>
        <script src="card-modal.js" defer />
      </body>
    </html>
  )
}
