import type { FunctionalComponent, ComponentChildren } from 'preact'

interface LayoutProps {
  title: string
  children: ComponentChildren
}

export const Layout: FunctionalComponent<LayoutProps> = ({ title, children }) => {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>{`${title} | MTG Decks`}</title>
        <link rel="stylesheet" href="styles.css" />
      </head>
      <body className="min-h-screen p-8 flex flex-col">
        <header className="mb-8">
          <nav>
            <a href="index.html" className="text-blue-400 hover:text-blue-300">
              Home
            </a>
          </nav>
        </header>
        <main className="grow">{children}</main>
        <footer className="mt-16 border-t border-gray-800 pt-8 text-center text-sm text-gray-500">
          <p>
            This site was generated by{' '}
            <span className="font-semibold text-gray-400">ritual-cli</span>.
          </p>
          <p className="mt-1">Copyright &copy; 2026 Ryan Peters.</p>
        </footer>
        <script src="tooltip.js" defer />
      </body>
    </html>
  )
}
